# Use uma imagem base com suporte ao Tomcat
FROM tomcat:9.0.56-jdk17-temurin


# Exponha a porta 8080 (a porta padrão do Tomcat)
EXPOSE 8080

# Execute o Tomcat ao iniciar o contêiner
CMD ["catalina.sh", "run"]